Fix page selection after limit was changed
margaritachepikova/md-data-table pull request #1
Opened 2018-07-30 09:09 UTC by margaritachepikova

2018-07-31 15:35 UTC, andyYatskov approved these changes

2018-08-01 15:24 UTC, dan-luk requested changes

2018-08-01 15:24 UTC, dan-luk commented on .gitignore
> +.idea
remove these additions

2018-08-01 15:24 UTC, dan-luk commented on dist/md-data-table.js
> +angular.module('md-table-pagination.html', []).run(['$templateCache', function ($templateCache) {
rollback these

2018-08-01 15:24 UTC, dan-luk commented on package-lock.json
> +{
why add this

2018-08-02 08:54 UTC, margaritachepikova commented on dist/md-data-table.js
> +angular.module('md-table-pagination.html', []).run(['$templateCache', function ($templateCache) {
Grunt add these spaces when updating the build. I have not found how to turn off this feature. Maybe it is caused by new Grunt version.

2018-08-02 09:00 UTC, margaritachepikova commented on .gitignore
> +.idea
IntelliJ IDEA adds its folders to commit. So I add `.idea` directory to the list of ignored files.

2018-08-02 13:39 UTC, dan-luk commented on .gitignore
> +.idea
Remove it!  It is fine within our team where everyone uses idea, but may not be fine for other projects.

If you still want your personal files ignored - https://medium.com/@peter_graham/how-to-create-a-local-gitignore-1b19f083492b

2018-08-02 17:17 UTC, dan-luk approved these changes

2018-08-03 08:23 UTC, merged